name: CI/CD TaskManager

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run PHPUnit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer, phpunit

      - name: Install Dependencies
        run: composer install --no-progress --no-suggest

      - name: Run Tests
        run: vendor/bin/phpunit --testdox

  deploy:
    name: Deploy to Production
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy Application
        run: |
          echo "Iniciando o deploy..."
          mkdir -p ~/deploy/taskmanager
          cp -r src ~/deploy/taskmanager/
          echo "Deploy concluído!"
